const jwt = require('../utils/jwt')
const ChatSession = require('../models/ChatSession')
const aiClient = require('./aiClient')

const generateChatbotToken = async (userId) => {
  // Generate short-lived token for chatbot access (15 minutes)
  const token = jwt.generateToken({ userId, type: 'chatbot' }, { expiresIn: '15m' })
  return token
}

/**
 * Handle one chat turn: find or open the session, ask the AI service, persist.
 *
 * `sessionId` is an opaque string generated by the browser (e.g.
 * "session-1788185187684-o6q91ysip"). `chat_sessions.id` is a SERIAL integer,
 * so passing it straight to a lookup made Postgres raise
 * `invalid input syntax for type integer` and the request 500'd — every
 * message sent from the UI failed. The client's key is stored alongside the
 * row instead, and the integer id stays internal.
 */
const sendMessage = async (userId, sessionId, message) => {
  let session = null
  if (sessionId) {
    session = await ChatSession.findBySessionKey(userId, String(sessionId))
  }
  if (!session) {
    session = await ChatSession.create({
      user_id: userId,
      session_key: sessionId ? String(sessionId) : null,
    })
  }

  const ai = await aiClient.sendMessage({
    sessionId: sessionId || session.id,
    message,
    userId,
  })

  await ChatSession.addMessage(session.id, {
    user_message: message,
    bot_response: ai.message,
    timestamp: new Date(),
  })

  return {
    message: ai.message,
    sessionId: sessionId || String(session.id),
    appointmentData: ai.appointmentData,
  }
}

module.exports = {
  generateChatbotToken,
  sendMessage,
}
